### ISSUE TITLE
I want to use pjsua2 in python, but the compilation of pjproject-2.7 failed. All attempts have failed. Do you have a compiled package or compilation steps that can help me? Thank you very much. My email: 110900144@qq.com

### ISSUE THREAD

**Issue by jindacheng** [dennisguse/pjsip#11]
I want to use pjsua2 in python, but the compilation of pjproject-2.7 failed. All attempts have failed. Do you have a compiled package or compilation steps that can help me? Thank you very much. My email: 110900144@qq.com

**Comment by dennisguse** [comment]
Hi, I cannot help you with this problem as I do not use pjproject at the moment (and have no plans at the moment). Sorry.
